import 'package:flutter/material.dart';
import 'package:match_track/core/domain/model/player.dart';
import 'package:match_track/features/teams/ui/widgets/add_image_box.dart';

class PlayerFormPage extends StatefulWidget {
  final String teamSport;
  final String teamCategory;

  const PlayerFormPage({super.key, required this.teamSport, required this.teamCategory});

  @override
  State<PlayerFormPage> createState() => _PlayerFormPageState();
}

class _PlayerFormPageState extends State<PlayerFormPage> {
  final _formKey = GlobalKey<FormState>();
  final nameCtrl = TextEditingController();
  final jerseyCtrl = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Añadir jugador")),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              AddImageBox(onTap: () {}),
              const SizedBox(height: 12),
              TextFormField(
                controller: nameCtrl,
                decoration: const InputDecoration(labelText: "Nombre"),
                validator: (v) =>
                    v == null || v.isEmpty ? "Ingrese un nombre" : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: jerseyCtrl,
                decoration:
                    const InputDecoration(labelText: "Número de camiseta"),
                keyboardType: TextInputType.number,
                validator: (v) => v == null || v.isEmpty
                    ? "Ingrese un número de camiseta"
                    : null,
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    final player = Player(
                      id: '', // Will be generated by backend
                      name: nameCtrl.text,
                      sport: widget.teamSport,
                      category: widget.teamCategory,
                      jersey_number: jerseyCtrl.text,
                      team_id: '', // Will be assigned on team creation
                    );
                    Navigator.pop(context, player);
                  }
                },
                child: const Text("Guardar jugador"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}